/**
 * Windmill backend client.
 *
 * In production, this is auto-generated by `wmill app dev`.
 * This placeholder provides typed wrappers around backend runnables
 * so the frontend can call them during development.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type BackendFn = (args: Record<string, unknown>) => Promise<any>;

/**
 * Call a Windmill backend runnable by name.
 * In the Windmill runtime, `window.__wmill_backend` is injected automatically.
 * During local dev, this falls back to a direct HTTP call.
 */
async function callBackend(name: string, args: Record<string, unknown>): Promise<unknown> {
  // Windmill injects this at runtime for full-code apps
  const wmillBackend = (window as Record<string, unknown>).__wmill_backend as
    | ((name: string, args: Record<string, unknown>) => Promise<unknown>)
    | undefined;

  if (wmillBackend) {
    return wmillBackend(name, args);
  }

  // Fallback for local development without Windmill runtime
  console.warn(`[wmill] Backend "${name}" called outside Windmill runtime. Args:`, args);
  throw new Error(`Backend runnable "${name}" is not available outside Windmill.`);
}

function createBackendProxy(name: string): BackendFn {
  return (args: Record<string, unknown>) => callBackend(name, args);
}

export const backend = {
  okx_proxy: createBackendProxy('okx_proxy'),
  gemini_proxy: createBackendProxy('gemini_proxy'),
  sync_trades: createBackendProxy('sync_trades'),
  sync_balances: createBackendProxy('sync_balances'),
};
